// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP1lxrL6plMUHTY05Mnz9tdjVpe8HbbBw',
    appId: '1:697685628697:web:434422abbc07c7c1265788',
    messagingSenderId: '697685628697',
    projectId: 'fir-demo-9d1f7',
    authDomain: 'fir-demo-9d1f7.firebaseapp.com',
    databaseURL: 'https://fir-demo-9d1f7-default-rtdb.firebaseio.com',
    storageBucket: 'fir-demo-9d1f7.appspot.com',
    measurementId: 'G-3MQ52260SP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwgDbCFFQbh-3_mDAvBecBSdG0-3zEtrI',
    appId: '1:697685628697:android:c9cbe817ddf44432265788',
    messagingSenderId: '697685628697',
    projectId: 'fir-demo-9d1f7',
    databaseURL: 'https://fir-demo-9d1f7-default-rtdb.firebaseio.com',
    storageBucket: 'fir-demo-9d1f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh-pcPT9Fque70T4yFCXT--6h3mJLVkdQ',
    appId: '1:697685628697:ios:6d063dd0b8ced7e3265788',
    messagingSenderId: '697685628697',
    projectId: 'fir-demo-9d1f7',
    databaseURL: 'https://fir-demo-9d1f7-default-rtdb.firebaseio.com',
    storageBucket: 'fir-demo-9d1f7.appspot.com',
    iosClientId: '697685628697-h89oj0m1dg386m193n66kq1l51ddovua.apps.googleusercontent.com',
    iosBundleId: 'com.example.csasc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh-pcPT9Fque70T4yFCXT--6h3mJLVkdQ',
    appId: '1:697685628697:ios:6d063dd0b8ced7e3265788',
    messagingSenderId: '697685628697',
    projectId: 'fir-demo-9d1f7',
    databaseURL: 'https://fir-demo-9d1f7-default-rtdb.firebaseio.com',
    storageBucket: 'fir-demo-9d1f7.appspot.com',
    iosClientId: '697685628697-h89oj0m1dg386m193n66kq1l51ddovua.apps.googleusercontent.com',
    iosBundleId: 'com.example.csasc',
  );
}
